# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # ------------------------------
  # Box Ubuntu 20.04 LTS
  # ------------------------------
  config.vm.box = "ubuntu/focal64"

  # ------------------------------
  # Réseau privé (host-only)
  # ------------------------------
  config.vm.network "private_network", ip: "10.2.33.17"

  # ------------------------------
  # Réseau public (bridged)
  # ------------------------------
  config.vm.network "public_network", bridge: "Intel(R) Ethernet Connection (16) I219-LM"

  # ------------------------------
  # Configuration VirtualBox
  # ------------------------------
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1600"
  end

  # ------------------------------
  # Provisionnement Shell via script externe
  # ------------------------------
  config.vm.provision "shell", path: "provision.sh"

end